name: poc-test 
on:
  push:
      branches:
        - "experimental/workflow-check"
jobs:
  build:
    name: Build and publish Python 🐍 distributions 📦 to PyPI and TestPyPI
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        
    - name: Install pypa/build
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade setuptools
        python -m pip install build pipenv tox --user

    - name: Build a binary wheel and a source tarball
      run: >-
        make build
